requirements:
- id: f7d250bf-5b3e-4ec3-8bd5-2bee2c4b7bb9
  spec_id: SPEC-001
  title: Implement user authentication
  description: The system should support user authentication via username/password and OAuth
  status: Draft
  priority: High
  owner: Joe Mooney
  feature: 1-Authentication
  created_at: 2025-11-19T19:41:14.018536570Z
  modified_at: 2025-11-19T19:41:14.018536570Z
  req_type: Functional
  dependencies: []
  tags:
  - security
  - auth
  - user
  relationships:
  - rel_type: Verifies
    target_id: 819258b2-9624-4046-9f52-0b00af26c046
  - rel_type: Parent
    target_id: 013cc55c-3123-42b2-81df-d930cf9eb288
- id: 013cc55c-3123-42b2-81df-d930cf9eb288
  spec_id: SPEC-002
  title: Implement requirements export
  description: The system should allow exporting requirements to various formats (PDF, CSV, JSON)
  status: Draft
  priority: Medium
  owner: Joe Mooney
  feature: 2-Reporting
  created_at: 2025-11-19T19:41:32.523506980Z
  modified_at: 2025-11-25T05:33:40.270050473Z
  req_type: Functional
  dependencies: []
  tags:
  - reporting
  - export
  relationships:
  - rel_type: Child
    target_id: f7d250bf-5b3e-4ec3-8bd5-2bee2c4b7bb9
- id: 819258b2-9624-4046-9f52-0b00af26c046
  spec_id: SPEC-003
  title: Test Non-Interactive
  description: This is a test requirement for non-interactive mode
  status: Draft
  priority: Medium
  owner: ''
  feature: 3-Testing
  created_at: 2025-11-19T20:14:34.464156508Z
  modified_at: 2025-11-19T20:14:34.464156508Z
  req_type: Functional
  dependencies: []
  tags: []
- id: b8ebfc9e-b93e-4644-b1d5-79139465107d
  spec_id: SPEC-004
  title: Password Strength Rules
  description: System should enforce password strength rules
  status: Draft
  priority: Medium
  owner: ''
  feature: 4-Security
  created_at: 2025-11-19T20:28:24.824469396Z
  modified_at: 2025-11-19T20:28:24.824469396Z
  req_type: Functional
  dependencies: []
  tags: []
  relationships:
  - rel_type: !Custom implements
    target_id: 59d7c79a-2796-4e9a-866b-d39d02370e3c
- id: 59d7c79a-2796-4e9a-866b-d39d02370e3c
  spec_id: SPEC-005
  title: Default Feature Test
  description: Testing default feature when REQ_FEATURE is not set
  status: Draft
  priority: Medium
  owner: ''
  feature: 5-Uncategorized
  created_at: 2025-11-19T20:28:37.514068238Z
  modified_at: 2025-11-19T20:28:37.514068238Z
  req_type: Functional
  dependencies: []
  tags: []
- id: 2c5b7c16-0b9b-4090-9bf0-5c3ee81855fb
  spec_id: SPEC-006
  title: Explicit Feature
  description: Testing setting feature on command line
  status: Draft
  priority: Medium
  owner: ''
  feature: 6-UI
  created_at: 2025-11-19T20:28:51.559887018Z
  modified_at: 2025-11-19T20:28:51.559887018Z
  req_type: Functional
  dependencies: []
  tags: []
- id: ce794d40-9918-48a9-83c2-f8e1d0bb2f40
  spec_id: SPEC-007
  title: Feature Precedence
  description: Testing which feature takes precedence
  status: Draft
  priority: Medium
  owner: ''
  feature: 7-API
  created_at: 2025-11-19T20:29:04.405708451Z
  modified_at: 2025-11-19T20:29:04.405708451Z
  req_type: Functional
  dependencies: []
  tags: []
- id: e1c4ca48-7985-4fdd-bcd1-a17e8a3dcf77
  spec_id: SPEC-008
  title: Example Requirement
  description: This is a test requirement
  status: Draft
  priority: Medium
  owner: ''
  feature: 5-Uncategorized
  created_at: 2025-11-19T22:33:36.028263237Z
  modified_at: 2025-11-19T22:33:36.028263237Z
  req_type: Functional
  dependencies: []
  tags: []
- id: 28fe33c5-87f6-4883-ae5f-a4b2a5c94104
  spec_id: SPEC-009
  title: Auth Requirement
  description: This is a test requirement for the auth project
  status: Draft
  priority: Medium
  owner: ''
  feature: 5-Uncategorized
  created_at: 2025-11-19T22:33:49.932270075Z
  modified_at: 2025-11-19T22:33:49.932270075Z
  req_type: Functional
  dependencies: []
  tags: []
next_feature_number: 10
next_spec_number: 12
